USE [Computer_Components]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (0, 1, ADA, Cardano, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (1, 2, BTC, Bitcoin, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (2, 3, DASH, DASH, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (3, 4, DOGE, Dogecoin, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (4, 5, EOS, EOS, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (5, 6, ETH, Ethereum, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (6, 7, LTC, Litecoin, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (7, 8, MIOTA, IOTA, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (8, 9, NEO, NEO, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (9, 10, TRX, TRON, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (10, 11, USDT, Tether, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (11, 12, XEM, NEM, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (12, 13, XLM, Stellar, 0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (13, 14, XMR, Monero, 1)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_CRYPTO_DATA (Id, Code, Currency_Name, Is_Mineable)
VALUES (14, 15, XRP, Ripple, 0)
GO
