USE [Computer_Components]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (0, 1, 1stWave Technologies)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (1, 2, Adorama)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (2, 3, Alternate)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (3, 4, Alternate Italia)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (4, 5, Alza)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (5, 6, Aquatuning)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (6, 7, Aquila Technology)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (7, 8, Aria PC)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (8, 9, ARLT)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (9, 10, Ascent Technology)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (10, 11, AWD-IT)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (11, 12, AX86 Gaming Systems)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (12, 13, B H)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (13, 14, Best Buy)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (14, 15, Box Limited)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (15, 16, BT Shop)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (16, 17, Bytes At Work)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (17, 18, Caseking)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (18, 19, CCL Computers)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_MERCHANT (Id, Merchant)
VALUES (19, 20, Centre Com)
GO
