USE [Computer_Components]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (0, 1, au, AUD)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (1, 2, be, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (2, 3, ca, CAD)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (3, 4, de, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (4, 5, es, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (5, 6, fr, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (6, 7, ie, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (7, 8, it, EUR)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (8, 9, nz, NZD)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (9, 10, uk, GBP)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_REGION (Id, Code, Currency)
VALUES (10, 11, us, USD)
GO
