USE [Computer_Components]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (0, 2, ADATA, Adata, DDR, 333, 1.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (1, 1, ADATA, Adata, DDR, 400, 0.5)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (2, 3, ADATA, Adata, DDR, 400, 1.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (3, 4, ADATA, Adata, DDR, 400, 2.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (4, 5, ADATA, Adata, DDR2, 667, 1.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (5, 7, ADATA, Adata, DDR2, 667, 2.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (6, 6, ADATA, Adata, DDR2, 800, 1.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (7, 8, ADATA, Adata, DDR2, 800, 2.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (8, 9, ADATA, Adata, DDR2, 800, 4.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (9, 10, ADATA, Adata, DDR3, 1066, 2.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (10, 11, ADATA, Adata, DDR3, 1333, 2.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (11, 12, ADATA, Adata, DDR3, 1333, 4.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (12, 14, ADATA, Adata, DDR3, 1333, 8.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (13, 13, ADATA, Adata, DDR3, 1600, 4.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (14, 15, ADATA, Adata, DDR3, 1600, 8.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (15, 22, ADATA, Adata, DDR4, 2133, 16.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (16, 16, ADATA, Adata, DDR4, 2400, 8.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (17, 27, ADATA, Adata, DDR4, 2400, 32.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (18, 17, ADATA, Adata, DDR4, 2666, 8.0)
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
INSERT INTO DIM_RAM_PROD (Id, Manufacturer, RAM_Name, Memory_Type, Speed, Capacity)
VALUES (19, 18, ADATA, Adata, DDR4, 3000, 8.0)
GO
